repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -w
        language: system
        types: [go]
      - id: go-vet
        name: go vet
        entry: bash -c 'cd src/backend && go vet ./...'
        language: system
        types: [go]
        pass_filenames: false

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [--enable=all, --shell=bash]
        files: ^(src/wrappers|tests)\/.*\.(bash|sh)$
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt -i 4 -w
        language: system
        files: ^(src/wrappers|tests)\/.*\.(bash|sh)$

  - repo: https://github.com/specture-system/specture
    rev: v0.0.1
    hooks:
      - id: validate-specs
