name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Run go vet
        run: cd src/backend && go vet ./...

      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: './**/*.fish ./**/*.zsh'
        env:
          SHELLCHECK_OPTS: --enable=all --shell=bash

  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - uses: mfinelli/setup-shfmt@v4

      - name: Run go fmt
        run: cd src/backend && go fmt ./... && git diff --exit-code

      - name: Run shfmt
        run: shfmt -i 4 -w . && git diff --exit-code
