name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: jdx/mise-action@v4
        with:
          install_args: go shellcheck

      - name: Run go vet
        run: cd src/backend && go vet ./...

      - name: Run ShellCheck
        run: shellcheck --enable=all src/wrappers/*.bash tests/**/*.bash tests/**/*.sh ci/*.sh install.sh

  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: jdx/mise-action@v4
        with:
          install_args: go shfmt

      - name: Run go fmt
        run: cd src/backend && go fmt ./... && git diff --exit-code

      - name: Run shfmt
        run: shfmt -i 4 -w src/wrappers/*.bash tests/**/*.bash tests/**/*.sh ci/*.sh install.sh && git diff --exit-code
