name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run unit tests
        run: cd src/backend && go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [bash, zsh, fish]
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get install -y zsh fish

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build binary
        run: cd src/backend && go build -o ../../bin/to-backend ./cmd

      - name: Run integration tests
        run: bash tests/integration/runner.sh ${{ matrix.shell }}
